name: Code checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Run code checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os:
          - ubuntu-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.0

      - run: poetry install
      - run: poetry run poe codestyle
      - run: poetry run poe typecheck
      - run: poetry run poe liccheck
