name: Code checks
on:
  push:
    branches:
      - main
      - b0.*
  pull_request:
    branches:
      - main
      - b0.*

jobs:
  check:
    name: Run code checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os:
          - ubuntu-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: poetry run poe checks_codestyle
      - run: poetry run poe checks_typing
      - run: poetry run poe checks_license
