name: Unit tests
on:
  push:
    branches:
      - main
      - b0.*
  pull_request:
    branches:
      - main
      - b0.*

jobs:
  unittest:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        os:
          - ubuntu-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.0

      - run: poetry install
      - run: poetry run poe tests_unit
